# Generated by Django 5.2.6 on 2026-08-20 17:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='النقطة')),
                ('status', models.CharField(choices=[('ENTERED', 'مسجلة'), ('ABSENT', 'غائبة'), ('EXCUSED', 'غياب مبرر'), ('EXEMPT', 'معفاة'), ('MISSING', 'لم تدخل بعد')], default='MISSING', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.curriculum', verbose_name='مادة الفصل')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.enrollment', verbose_name='التسجيل')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades_entered', to=settings.AUTH_USER_MODEL, verbose_name='أدخلها')),
            ],
            options={
                'verbose_name': 'نقطة',
                'verbose_name_plural': 'النقاط',
                'ordering': ['enrollment', 'curriculum'],
            },
        ),
        migrations.CreateModel(
            name='GradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('old_status', models.CharField(blank=True, max_length=10)),
                ('new_status', models.CharField(max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='السبب')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_changes', to=settings.AUTH_USER_MODEL, verbose_name='غيّرها')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='grading.grade', verbose_name='النقطة')),
            ],
            options={
                'verbose_name': 'سجل تغيير النقطة',
                'verbose_name_plural': 'سجل تغييرات النقاط',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='GradingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='رقم النسخة')),
                ('max_grade', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='النقطة القصوى')),
                ('pass_threshold', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='عتبة النجاح')),
                ('compensation_floor', models.DecimalField(decimal_places=2, default=7, max_digits=5, verbose_name='الحد الأدنى للتعويض')),
                ('ranking_mode', models.CharField(choices=[('DENSE', 'متتابع (1، 2، 3، 3، 4)'), ('STANDARD', 'تنافسي (1، 2، 3، 3، 5)')], default='DENSE', max_length=10, verbose_name='طريقة الترتيب')),
                ('absence_policy', models.CharField(choices=[('ZERO', 'تحتسب صفرا'), ('EXCLUDE', 'تستثنى من المعدل')], default='ZERO', max_length=10, verbose_name='معاملة الغياب')),
                ('rounding_decimals', models.PositiveSmallIntegerField(default=2, verbose_name='عدد الأرقام العشرية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(blank=True, help_text='اتركه فارغا لتطبيق القاعدة على جميع الأقسام.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_rules', to='academics.section', verbose_name='القسم')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_rules', to='academics.academicyear', verbose_name='السنة الدراسية')),
            ],
            options={
                'verbose_name': 'قاعدة التقويم',
                'verbose_name_plural': 'قواعد التقويم',
                'ordering': ['year', 'section', '-version'],
            },
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['curriculum', 'status'], name='grading_gra_curricu_6d34ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('enrollment', 'curriculum'), name='une_note_par_etudiante_et_matiere_de_fasl'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ENTERED'), ('value__isnull', False)), models.Q(models.Q(('status', 'ENTERED'), _negated=True), ('value__isnull', True)), _connector='OR'), name='valeur_coherente_avec_statut'),
        ),
        migrations.AddIndex(
            model_name='gradehistory',
            index=models.Index(fields=['grade', '-changed_at'], name='grading_gra_grade_i_f4235a_idx'),
        ),
        migrations.AddConstraint(
            model_name='gradingrule',
            constraint=models.UniqueConstraint(fields=('year', 'section', 'version'), name='version_unique_par_annee_et_section'),
        ),
    ]
