# Generated by Django 5.2.6 on 2026-08-20 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_semester_current_session'),
        ('grading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grade',
            name='une_note_par_etudiante_et_matiere_de_fasl',
        ),
        migrations.RemoveConstraint(
            model_name='gradingrule',
            name='version_unique_par_annee_et_section',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='grading_gra_curricu_6d34ba_idx',
        ),
        migrations.AddField(
            model_name='grade',
            name='session',
            field=models.CharField(choices=[('NORMAL', 'الدورة العادية'), ('RESIT', 'الدورة الاستدراكية')], default='NORMAL', max_length=10, verbose_name='الدورة'),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='session',
            field=models.CharField(choices=[('NORMAL', 'الدورة العادية'), ('RESIT', 'الدورة الاستدراكية')], default='NORMAL', max_length=10, verbose_name='الدورة'),
        ),
        migrations.AddField(
            model_name='gradingrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grading_rules_created', to=settings.AUTH_USER_MODEL, verbose_name='أقرّها'),
        ),
        migrations.AddField(
            model_name='gradingrule',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملاحظة المداولة'),
        ),
        migrations.AddField(
            model_name='gradingrule',
            name='resit_policy',
            field=models.CharField(choices=[('BEST', 'أعلى النقطتين'), ('REPLACE', 'تعوّض نقطة الدورة العادية'), ('BEST_CAPPED', 'أعلى النقطتين بسقف عتبة النجاح')], default='BEST', max_length=15, verbose_name='احتساب نقطة الاستدراك'),
        ),
        migrations.AddField(
            model_name='gradingrule',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='اتركه فارغا لتطبيق القاعدة على كل فصول السنة.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_rules', to='academics.semester', verbose_name='الفصل'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['curriculum', 'session', 'status'], name='grading_gra_curricu_50766e_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('enrollment', 'curriculum', 'session'), name='une_note_par_etudiante_matiere_et_dorra'),
        ),
        migrations.AddConstraint(
            model_name='gradingrule',
            constraint=models.UniqueConstraint(fields=('year', 'section', 'semester', 'version'), name='version_unique_par_annee_section_et_fasl'),
        ),
    ]
