# Generated by Django 5.2.6 on 2026-08-20 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'مدير'), ('ASSISTANT', 'مساعد الإدارة'), ('TEACHER', 'أستاذ'), ('STUDENT', 'طالبة')], default='STUDENT', max_length=10, verbose_name='الدور'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'مدير'), ('ASSISTANT', 'مساعد الإدارة'), ('TEACHER', 'أستاذ'), ('STUDENT', 'طالبة')], max_length=10, verbose_name='الدور')),
                ('permission', models.CharField(choices=[('notes.saisir', 'إدخال النقاط'), ('notes.consulter', 'الاطلاع على النقاط والنتائج'), ('deliberation.gerer', 'المداولة والعتبات والنشر'), ('structure.gerer', 'البنية البيداغوجية والضوارب'), ('etudiantes.gerer', 'ملفات الطالبات والتسجيل'), ('annees.gerer', 'السنوات الدراسية'), ('journal.consulter', 'سجل تغييرات النقاط'), ('comptes.gerer', 'الحسابات والصلاحيات'), ('resultats.personnels', 'الاطلاع على نتائجها')], max_length=40, verbose_name='الصلاحية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_accordees', to=settings.AUTH_USER_MODEL, verbose_name='منحها')),
            ],
            options={
                'verbose_name': 'صلاحية دور',
                'verbose_name_plural': 'صلاحيات الأدوار',
                'ordering': ['role', 'permission'],
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='une_permission_par_role')],
            },
        ),
    ]
