# Generated by Django 5.2.6 on 2026-08-20 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_attributions_par_defaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('notes.saisir', 'إدخال النقاط'), ('notes.consulter', 'الاطلاع على النقاط والنتائج'), ('deliberation.gerer', 'المداولة والعتبات والنشر'), ('structure.gerer', 'البنية البيداغوجية والضوارب'), ('etudiantes.gerer', 'ملفات الطالبات والتسجيل'), ('annees.gerer', 'السنوات الدراسية'), ('journal.consulter', 'سجل تغييرات النقاط'), ('comptes.gerer', 'الحسابات والصلاحيات'), ('resultats.personnels', 'الاطلاع على نتائجها')], max_length=40, verbose_name='الصلاحية')),
                ('granted', models.BooleanField(default=True, verbose_name='ممنوحة')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions_accordees', to=settings.AUTH_USER_MODEL, verbose_name='قررها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'صلاحية فردية',
                'verbose_name_plural': 'الصلاحيات الفردية',
                'ordering': ['user', 'permission'],
                'constraints': [models.UniqueConstraint(fields=('user', 'permission'), name='une_exception_par_utilisateur_et_permission')],
            },
        ),
    ]
