# Generated by Django 5.2.6 on 2026-08-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_droits_assistant_et_tableau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.CharField(choices=[('tableau.consulter', 'لوحة القيادة'), ('notes.saisir', 'إدخال النقاط'), ('notes.consulter', 'الاطلاع على النقاط والنتائج'), ('deliberation.gerer', 'المداولة والعتبات والنشر'), ('structure.gerer', 'البنية البيداغوجية والضوارب'), ('etudiantes.gerer', 'ملفات الطالبات والتسجيل'), ('annees.gerer', 'السنوات الدراسية'), ('journal.consulter', 'سجل تغييرات النقاط'), ('comptes.gerer', 'الحسابات والصلاحيات'), ('resultats.personnels', 'الاطلاع على نتائجها')], max_length=40, verbose_name='الصلاحية'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='permission',
            field=models.CharField(choices=[('tableau.consulter', 'لوحة القيادة'), ('notes.saisir', 'إدخال النقاط'), ('notes.consulter', 'الاطلاع على النقاط والنتائج'), ('deliberation.gerer', 'المداولة والعتبات والنشر'), ('structure.gerer', 'البنية البيداغوجية والضوارب'), ('etudiantes.gerer', 'ملفات الطالبات والتسجيل'), ('annees.gerer', 'السنوات الدراسية'), ('journal.consulter', 'سجل تغييرات النقاط'), ('comptes.gerer', 'الحسابات والصلاحيات'), ('resultats.personnels', 'الاطلاع على نتائجها')], max_length=40, verbose_name='الصلاحية'),
        ),
    ]
