# Generated by Django 5.2.6 on 2026-08-21 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_rolepermission_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='اسم المستخدم')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='المستوى')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='بداية الإقفال')),
                ('until', models.DateTimeField(db_index=True, verbose_name='نهاية الإقفال')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الفتح')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lockouts_released', to=settings.AUTH_USER_MODEL, verbose_name='فتحه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lockouts', to=settings.AUTH_USER_MODEL, verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'إقفال حساب',
                'verbose_name_plural': 'الحسابات المقفلة',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='اسم المستخدم')),
                ('outcome', models.CharField(choices=[('SUCCESS', 'نجاح'), ('BAD_PASSWORD', 'كلمة سر خاطئة'), ('UNKNOWN_USER', 'مستخدم غير معروف'), ('INACTIVE', 'حساب معطل'), ('LOCKED', 'محاولة أثناء الإقفال')], db_index=True, max_length=15, verbose_name='النتيجة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='المتصفح')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التاريخ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL, verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'محاولة دخول',
                'verbose_name_plural': 'سجل الدخول',
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['username', '-at'], name='tentative_par_compte'), models.Index(fields=['outcome', '-at'], name='tentative_par_issue')],
            },
        ),
    ]
