# Generated by Django 5.2.6 on 2026-08-20 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='accounts.student', verbose_name='الطالبة'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.academicyear', verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.section', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curricula', to='academics.section', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicyear', verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='academics.semester', verbose_name='الفصل'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curricula', to='academics.subject', verbose_name='المادة'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.curriculum', verbose_name='مادة الفصل'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='accounts.teacher', verbose_name='الأستاذ'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'year'), name='une_section_par_etudiante_et_annee'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('year', 'number'), name='fasl_unique_par_annee'),
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(fields=('section', 'semester', 'subject'), name='une_matiere_une_fois_par_section_et_fasl'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'curriculum'), name='une_affectation_unique'),
        ),
    ]
