# Generated by Django 5.2.6 on 2026-08-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_curriculum_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='current_session',
            field=models.CharField(choices=[('NORMAL', 'الدورة العادية'), ('RESIT', 'الدورة الاستدراكية')], default='NORMAL', max_length=10, verbose_name='الدورة الجارية'),
        ),
    ]
