# Generated by Django 5.2.6 on 2026-09-07 17:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المسابقة')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='رمز العرض العام')),
                ('state', models.CharField(choices=[('DRAFT', 'قيد التحضير'), ('RUNNING', 'جارية'), ('FINISHED', 'منتهية')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('turn_seconds', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)], verbose_name='مدة الدور بالثواني')),
                ('show_question', models.BooleanField(default=True, verbose_name='عرض السؤال للجمهور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بداية المسابقة')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='نهاية المسابقة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitions_creees', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'مسابقة',
                'verbose_name_plural': 'المسابقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المجموعة')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('color', models.CharField(default='#006633', max_length=7, verbose_name='اللون')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='competition.competition', verbose_name='المسابقة')),
            ],
            options={
                'verbose_name': 'مجموعة',
                'verbose_name_plural': 'المجموعات',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='competition.competition', verbose_name='المسابقة')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='رقم الدور')),
                ('round_number', models.PositiveSmallIntegerField(verbose_name='الجولة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بداية الدور')),
                ('outcome', models.CharField(choices=[('PENDING', 'في انتظار القرار'), ('CORRECT', 'إجابة صحيحة'), ('NO_ANSWER', 'لم يجب')], default='PENDING', max_length=10, verbose_name='النتيجة')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القرار')),
                ('awarded_late', models.BooleanField(default=False, verbose_name='مُنح بعد انتهاء الوقت')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='competition.competition', verbose_name='المسابقة')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tours_decides', to=settings.AUTH_USER_MODEL, verbose_name='قرر')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='competition.group', verbose_name='المجموعة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='competition.question', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='TurnAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(unique=True, verbose_name='معرف العملية')),
                ('kind', models.CharField(choices=[('START', 'انطلاق الدور'), ('DECIDE', 'قرار')], max_length=10)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='competition.turn', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'عملية',
                'verbose_name_plural': 'العمليات',
                'ordering': ['received_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('competition', 'name'), name='un_nom_de_groupe_par_competition'),
        ),
        migrations.AddConstraint(
            model_name='turn',
            constraint=models.UniqueConstraint(fields=('competition', 'index'), name='un_tour_par_indice'),
        ),
    ]
