# Generated by Django 5.2.6 on 2026-09-07 23:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='kind',
            field=models.CharField(choices=[('CULTURELLE', 'مسابقة ثقافية'), ('POETIQUE', 'ندوة شعرية')], default='CULTURELLE', max_length=12, verbose_name='نوع المسابقة'),
        ),
        migrations.AddField(
            model_name='competition',
            name='rounds',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='عدد الجولات'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='competition.question', verbose_name='السؤال'),
        ),
    ]
