# Generated by Django 5.2.6 on 2026-09-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_competition_kind_competition_rounds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='rounds',
        ),
    ]
