# Generated by Django 5.2.6 on 2026-09-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_remove_competition_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, verbose_name='الإجابة'),
        ),
    ]
