# Generated by Django 5.2.6 on 2026-09-08 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='competition.group', verbose_name='المجموعة')),
            ],
            options={
                'verbose_name': 'عضوة',
                'verbose_name_plural': 'الأعضاء',
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('group', 'name'), name='un_nom_par_groupe')],
            },
        ),
    ]
