# Generated by Django 5.2.6 on 2026-09-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='tiebreak_round',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='جولة الحسم'),
        ),
    ]
