# Generated by Django 5.2.6 on 2026-09-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_turn_tiebreak_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='reserve_departage',
            field=models.BooleanField(default=False, verbose_name='حجز أسئلة لجولة الحسم'),
        ),
    ]
