# Generated by Django 5.2.6 on 2026-09-08 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_competition_reserve_departage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='reserve_departage',
        ),
        migrations.AddField(
            model_name='competition',
            name='questions_reservees',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='عدد أسئلة الحسم'),
        ),
    ]
